name: Notify on new issues

on:
  issues:
    types: [opened]
  workflow_dispatch: {}

jobs:
  gotify:
    runs-on: ubuntu-latest
    if: ${{ secrets.GOTIFY_URL != '' && secrets.GOTIFY_TOKEN != '' }}
    steps:
      - name: Send Gotify notification
        env:
          GOTIFY_URL: ${{ secrets.GOTIFY_URL }}
          GOTIFY_TOKEN: ${{ secrets.GOTIFY_TOKEN }}
          REPO: ${{ github.repository }}
          ACTOR: ${{ github.actor }}
          ISSUE_TITLE: ${{ github.event.issue.title }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          ISSUE_URL: ${{ github.event.issue.html_url }}
        run: |
          curl -sS -X POST "${GOTIFY_URL%/}/message?token=${GOTIFY_TOKEN}" \
            -H "Content-Type: application/json" \
            -d "$(jq -n \
              --arg title "New issue in ${REPO}" \
              --arg message "Issue #${ISSUE_NUMBER}: ${ISSUE_TITLE}"$'\n'"By: ${ACTOR}"$'\n'"${ISSUE_URL}" \
              --argjson priority 5 \
              '{title: $title, message: $message, priority: $priority}')"
